version: 0.0
os: linux
files:
    - source: /
      destination: {directory}/release

hooks:
    BeforeInstall:
        - location: scripts/prepare_release.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/configure_app.sh
          runas: root
          timeout: 300
        - location: scripts/change_permission.sh
          timeout: 300
          runas: root
        - location: scripts/move_symlink.sh
          timeout: 300
          runas: root
        - location: scripts/delete_old_release.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: scripts/start_server.sh
          timeout: 300
          runas: root
    ApplicationStop:
        - location: scripts/stop_server.sh
          timeout: 300
          runas: root